# Generated by celld. Python standard library only; no celld package required.
from __future__ import annotations
import asyncio
import json
from typing import Any
from urllib.parse import quote
from urllib.request import Request, urlopen
from urllib.error import HTTPError

_celld_unset: Any = object()

class CallError(RuntimeError):
    def __init__(self, status, body):
        self.status = status
        self.body = body
        super().__init__(f"Worker call failed ({status}): {body}")

class Client:
    def __init__(self, base_url: str, *, timeout: float = 30, key: str | None = None):
        self._celld_url = base_url.rstrip('/')
        self._celld_timeout = timeout
        self._celld_key = key

    def __getitem__(self, key: str):
        if not isinstance(key, str) or not 1 <= len(key) <= 1024:
            raise ValueError('object key must contain 1–1024 characters')
        return type(self)(self._celld_url, timeout=self._celld_timeout, key=key)

    def _celld_call(self, name, args):
        headers = {'content-type': 'application/json'}
        if self._celld_key is not None:
            headers['x-celld-object'] = quote(self._celld_key, safe='')
        request = Request(self._celld_url + '/' + quote(name, safe=''),
                          data=json.dumps(args).encode(), headers=headers)
        try:
            with urlopen(request, timeout=self._celld_timeout) as response:
                return json.load(response)['result']
        except HTTPError as error:
            raise CallError(error.code, error.read().decode()) from error
