[package]
name = "celld-monty"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
publish = false

[dependencies]
monty = { git = "https://github.com/pydantic/monty", rev = "af272c3116e2525249103f960b79086fd250bcef" }
monty-types = { git = "https://github.com/pydantic/monty", rev = "af272c3116e2525249103f960b79086fd250bcef" }
serde_json = "1"
ruff_python_ast = "=0.0.12"
ruff_python_parser = "=0.0.12"
